<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StatusPhrase;

class MorePhrasesSeeder extends Seeder
{
    public function run(): void
    {
        $phrases = [
            // academia
            ['category' => 'academia', 'author' => 'Arnold Schwarzenegger', 'phrase' => 'A força não vem de vencer. Suas lutas desenvolvem suas forças.'],
            ['category' => 'academia', 'author' => 'Muhammad Ali', 'phrase' => 'Não conte os dias, faça os dias contarem.'],
            ['category' => 'academia', 'author' => 'Ronnie Coleman', 'phrase' => 'Todo mundo quer ser fisiculturista, mas ninguém quer levantar pesos pesados.'],
            ['category' => 'academia', 'author' => 'Dorian Yates', 'phrase' => 'No final do dia, não é sobre o que você tem ou mesmo o que você realizou, mas quem você se tornou.'],
            ['category' => 'academia', 'author' => 'Bruce Lee', 'phrase' => 'Se você sempre coloca limites em tudo o que faz, isso se espalhará para o seu trabalho e para sua vida.'],
            ['category' => 'academia', 'author' => 'Jay Cutler', 'phrase' => 'Eu não treino para manter, eu treino para melhorar.'],
            ['category' => 'academia', 'author' => 'Lou Ferrigno', 'phrase' => 'A única pessoa que pode te dizer que você não consegue fazer algo é você mesmo.'],
            ['category' => 'academia', 'author' => 'Frank Zane', 'phrase' => 'A continuidade é a chave do sucesso no treinamento.'],
            ['category' => 'academia', 'author' => 'Phil Heath', 'phrase' => 'Ser o número um é treinar como se você fosse o número dois.'],
            ['category' => 'academia', 'author' => 'Flex Wheeler', 'phrase' => 'Sua genética determina o potencial, mas seu trabalho dita os resultados.'],
            ['category' => 'academia', 'author' => 'Kai Greene', 'phrase' => 'Os pensamentos tornam-se coisas.'],
            ['category' => 'academia', 'author' => 'Tom Platz', 'phrase' => 'Quando você acha que terminou, você está apenas na metade.'],
            ['category' => 'academia', 'author' => 'Sylvester Stallone', 'phrase' => 'Não importa o quão forte você bate, mas o quanto você aguenta apanhar e continuar.'],
            ['category' => 'academia', 'author' => 'Mike Tyson', 'phrase' => 'Disciplina é fazer o que você odeia, mas fazê-lo como se amasse.'],
            ['category' => 'academia', 'author' => 'Conor McGregor', 'phrase' => 'O talento não existe, somos todos iguais como seres humanos. Você pode ser qualquer pessoa se dedicar tempo.'],
            ['category' => 'academia', 'author' => 'Michael Jordan', 'phrase' => 'Algumas pessoas querem que aconteça, algumas desejam que aconteça, outras fazem acontecer.'],
            ['category' => 'academia', 'author' => 'Usain Bolt', 'phrase' => 'Eu treinei 4 anos para correr 9 segundos. Tem gente que não vê resultado em 2 meses e desiste.'],
            ['category' => 'academia', 'author' => 'Kobe Bryant', 'phrase' => 'A dedicação faz com que os sonhos se tornem realidade.'],
            ['category' => 'academia', 'author' => 'Vince Lombardi', 'phrase' => 'A diferença entre uma pessoa de sucesso e as outras não é a falta de força, nem de conhecimento, mas de vontade.'],
            ['category' => 'academia', 'author' => 'David Goggins', 'phrase' => 'Quando você acha que está no limite, você está apenas em 40% da capacidade do seu corpo.'],

            // boa-noite
            ['category' => 'boa-noite', 'author' => 'Victor Hugo', 'phrase' => 'A noite é a metade da vida e, por vezes, a melhor.'],
            ['category' => 'boa-noite', 'author' => 'Fernando Pessoa', 'phrase' => 'Durma bem, que o amanhã trará novas oportunidades de sorrir.'],
            ['category' => 'boa-noite', 'author' => 'William Shakespeare', 'phrase' => 'Desejo a você uma noite de paz, que os anjos guardem o seu sono.'],
            ['category' => 'boa-noite', 'author' => 'Clarice Lispector', 'phrase' => 'Que o silêncio da noite acalme o seu coração e traga paz para a sua mente.'],
            ['category' => 'boa-noite', 'author' => 'Machado de Assis', 'phrase' => 'O descanso é o melhor remédio para a alma fatigada.'],
            ['category' => 'boa-noite', 'author' => 'Mário Quintana', 'phrase' => 'Que a noite seja um manto de estrelas a cobrir os seus sonhos.'],
            ['category' => 'boa-noite', 'author' => 'Charles Chaplin', 'phrase' => 'Nunca esqueça de sorrir antes de dormir, pois amanhã é um novo dia.'],
            ['category' => 'boa-noite', 'author' => 'Cecília Meireles', 'phrase' => 'Entrego ao vento da noite as minhas preocupações e deixo a alma repousar.'],
            ['category' => 'boa-noite', 'author' => 'Antoine de Saint-Exupéry', 'phrase' => 'Olhe para o céu e veja como a noite pode ser bela.'],
            ['category' => 'boa-noite', 'author' => 'Cora Coralina', 'phrase' => 'A paz da noite é o prelúdio de um dia abençoado.'],
            ['category' => 'boa-noite', 'author' => 'Rubem Alves', 'phrase' => 'Dormir é viajar sem sair do lugar. Boa viagem!'],
            ['category' => 'boa-noite', 'author' => 'Carlos Drummond de Andrade', 'phrase' => 'Que o sono lhe traga as respostas que o dia não soube dar.'],
            ['category' => 'boa-noite', 'author' => 'Vinicius de Moraes', 'phrase' => 'A noite é um poema que se lê de olhos fechados.'],
            ['category' => 'boa-noite', 'author' => 'Luís Vaz de Camões', 'phrase' => 'O repouso é a recompensa dos justos.'],
            ['category' => 'boa-noite', 'author' => 'Florbela Espanca', 'phrase' => 'Nas estrelas leio o sossego que a minha alma precisa.'],
            ['category' => 'boa-noite', 'author' => 'Eça de Queirós', 'phrase' => 'Dorme, que o mundo gira sem a tua preocupação.'],
            ['category' => 'boa-noite', 'author' => 'Albert Einstein', 'phrase' => 'O sono profundo é o laboratório onde renovamos as nossas energias.'],
            ['category' => 'boa-noite', 'author' => 'Mahatma Gandhi', 'phrase' => 'A oração da noite fecha as portas das preocupações diárias.'],
            ['category' => 'boa-noite', 'author' => 'José Saramago', 'phrase' => 'Descansa, que o amanhã trará as suas próprias luzes e sombras.'],
            ['category' => 'boa-noite', 'author' => 'Ariano Suassuna', 'phrase' => 'Boa noite! E que o amanhã seja de sol e de riso franco.'],

            // bom-dia
            ['category' => 'bom-dia', 'author' => 'Marcus Aurelius', 'phrase' => 'Ao acordar de manhã, pense no precioso privilégio de estar vivo, de respirar, pensar, amar.'],
            ['category' => 'bom-dia', 'author' => 'Dalai Lama', 'phrase' => 'Cada dia é uma nova oportunidade para ser melhor.'],
            ['category' => 'bom-dia', 'author' => 'Walt Whitman', 'phrase' => 'Mantenha o seu rosto em direção à luz do sol e as sombras cairão atrás de você.'],
            ['category' => 'bom-dia', 'author' => 'Ralph Waldo Emerson', 'phrase' => 'Escreva no seu coração que cada dia é o melhor dia do ano.'],
            ['category' => 'bom-dia', 'author' => 'Clarice Lispector', 'phrase' => 'A vida é hoje. Não deixe para amanhã o bom dia que você pode dar hoje.'],
            ['category' => 'bom-dia', 'author' => 'Machado de Assis', 'phrase' => 'Um bom dia começa com a vontade de fazer acontecer.'],
            ['category' => 'bom-dia', 'author' => 'Mário Quintana', 'phrase' => 'O dia amanheceu. Que seja leve, que seja doce, que seja repleto de amor.'],
            ['category' => 'bom-dia', 'author' => 'Seneca', 'phrase' => 'Recebe cada dia como uma dádiva valiosa.'],
            ['category' => 'bom-dia', 'author' => 'Henry David Thoreau', 'phrase' => 'Desperte para as possibilidades deste novo dia.'],
            ['category' => 'bom-dia', 'author' => 'Cecília Meireles', 'phrase' => 'Há manhãs em que a alma acorda cantando.'],
            ['category' => 'bom-dia', 'author' => 'Carlos Drummond de Andrade', 'phrase' => 'O sol nasce para todos, mas a luz do dia ilumina quem está de olhos abertos.'],
            ['category' => 'bom-dia', 'author' => 'Vinicius de Moraes', 'phrase' => 'Bom dia, tristeza? Não, hoje o dia é de alegria.'],
            ['category' => 'bom-dia', 'author' => 'Cora Coralina', 'phrase' => 'Cada amanhecer é um recomeço cheio de esperança.'],
            ['category' => 'bom-dia', 'author' => 'Fernando Pessoa', 'phrase' => 'Que o seu dia tenha o encanto da poesia e a força da verdade.'],
            ['category' => 'bom-dia', 'author' => 'Albert Schweitzer', 'phrase' => 'O otimismo é a fé que leva à realização. Bom dia!'],
            ['category' => 'bom-dia', 'author' => 'Confúcio', 'phrase' => 'Não importa como o dia comece, o que importa é a atitude com que você o enfrenta.'],
            ['category' => 'bom-dia', 'author' => 'Lao-Tsé', 'phrase' => 'A manhã é o momento perfeito para esvaziar a mente e abraçar a serenidade.'],
            ['category' => 'bom-dia', 'author' => 'Mahatma Gandhi', 'phrase' => 'Seja a mudança que você deseja ver no mundo neste dia.'],
            ['category' => 'bom-dia', 'author' => 'Nelson Mandela', 'phrase' => 'Com um novo dia vêm novas forças e novos pensamentos.'],
            ['category' => 'bom-dia', 'author' => 'Steve Jobs', 'phrase' => 'Seu tempo é limitado, não o desperdice vivendo o dia de outra pessoa.'],

            // curtas
            ['category' => 'curtas', 'author' => 'Sêneca', 'phrase' => 'A sorte favorece os audazes.'],
            ['category' => 'curtas', 'author' => 'Júlio César', 'phrase' => 'Vim, vi, venci.'],
            ['category' => 'curtas', 'author' => 'Rene Descartes', 'phrase' => 'Penso, logo existo.'],
            ['category' => 'curtas', 'author' => 'Francis Bacon', 'phrase' => 'Saber é poder.'],
            ['category' => 'curtas', 'author' => 'Sócrates', 'phrase' => 'Conhece-te a ti mesmo.'],
            ['category' => 'curtas', 'author' => 'Horácio', 'phrase' => 'Carpe diem. Aproveite o dia.'],
            ['category' => 'curtas', 'author' => 'William Shakespeare', 'phrase' => 'Ser ou não ser, eis a questão.'],
            ['category' => 'curtas', 'author' => 'Albert Einstein', 'phrase' => 'A imaginação é mais importante que o conhecimento.'],
            ['category' => 'curtas', 'author' => 'Clarice Lispector', 'phrase' => 'Viver ultrapassa qualquer entendimento.'],
            ['category' => 'curtas', 'author' => 'Machado de Assis', 'phrase' => 'O tempo é um tecido invisível em que se pode bordar tudo.'],
            ['category' => 'curtas', 'author' => 'Fernando Pessoa', 'phrase' => 'O que vemos das coisas são as coisas.'],
            ['category' => 'curtas', 'author' => 'Mário Quintana', 'phrase' => 'A arte de viver é simplesmente a arte de conviver.'],
            ['category' => 'curtas', 'author' => 'Leonardo da Vinci', 'phrase' => 'O tempo dura bastante para aqueles que sabem aproveitá-lo.'],
            ['category' => 'curtas', 'author' => 'Oscar Wilde', 'phrase' => 'A vida é muito importante para ser levada a sério.'],
            ['category' => 'curtas', 'author' => 'Nietzsche', 'phrase' => 'O que não me destrói, torna-me mais forte.'],
            ['category' => 'curtas', 'author' => 'Buda', 'phrase' => 'A paz vem de dentro de você mesmo.'],
            ['category' => 'curtas', 'author' => 'Dalai Lama', 'phrase' => 'A compaixão é a base da felicidade.'],
            ['category' => 'curtas', 'author' => 'Platão', 'phrase' => 'O começo é a parte mais importante do trabalho.'],
            ['category' => 'curtas', 'author' => 'Voltaire', 'phrase' => 'O trabalho poupa-nos de três grandes males: tédio, vício e necessidade.'],
            ['category' => 'curtas', 'author' => 'Confúcio', 'phrase' => 'O silêncio é um amigo que nunca trai.'],

            // deus
            ['category' => 'deus', 'author' => 'Santo Agostinho', 'phrase' => 'Deus não espera que nos submetamos a Ele cegamente, mas sim com a inteligência.'],
            ['category' => 'deus', 'author' => 'C.S. Lewis', 'phrase' => 'Deus sussurra em nossos prazeres, fala em nossa consciência, mas grita em nossas dores.'],
            ['category' => 'deus', 'author' => 'Madre Teresa de Calcutá', 'phrase' => 'Deus não exige que tenhamos sucesso; ele apenas exige que tentemos.'],
            ['category' => 'deus', 'author' => 'São Tomás de Aquino', 'phrase' => 'A graça não destrói a natureza, mas a aperfeiçoa.'],
            ['category' => 'deus', 'author' => 'São Francisco de Assis', 'phrase' => 'Senhor, fazei-me instrumento de vossa paz.'],
            ['category' => 'deus', 'author' => 'A.W. Tozer', 'phrase' => 'O que vem à nossa mente quando pensamos em Deus é a coisa mais importante sobre nós.'],
            ['category' => 'deus', 'author' => 'Charles Spurgeon', 'phrase' => 'Deus é demasiado bom para ser cruel, demasiado sábio para errar.'],
            ['category' => 'deus', 'author' => 'Max Lucado', 'phrase' => 'Deus ama você do jeito que você é, mas Ele ama demais para deixá-lo assim.'],
            ['category' => 'deus', 'author' => 'Billy Graham', 'phrase' => 'A vontade de Deus não o levará aonde a graça de Deus não o possa proteger.'],
            ['category' => 'deus', 'author' => 'Rick Warren', 'phrase' => 'Você não é um acidente. Deus tinha um propósito para você desde o início.'],
            ['category' => 'deus', 'author' => 'Martinho Lutero', 'phrase' => 'Deus cria do nada. Portanto, enquanto o homem não for nada, Deus nada pode fazer com ele.'],
            ['category' => 'deus', 'author' => 'John Calvin', 'phrase' => 'Sem o conhecimento de si mesmo, não há conhecimento de Deus.'],
            ['category' => 'deus', 'author' => 'Dietrich Bonhoeffer', 'phrase' => 'Deus não nos salva do sofrimento, mas no sofrimento.'],
            ['category' => 'deus', 'author' => 'Corrie ten Boom', 'phrase' => 'Não há poço tão profundo que o amor de Deus não seja ainda mais profundo.'],
            ['category' => 'deus', 'author' => 'João Paulo II', 'phrase' => 'Não tenhais medo! Abri, melhor, escancarai as portas a Cristo!'],
            ['category' => 'deus', 'author' => 'Blaise Pascal', 'phrase' => 'Há um vazio com o formato de Deus no coração de cada homem.'],
            ['category' => 'deus', 'author' => 'Thomas Kempis', 'phrase' => 'Sem a graça de Deus, nada somos e nada podemos fazer.'],
            ['category' => 'deus', 'author' => 'Padre Pio', 'phrase' => 'Reza, espera e não te preocupes. A preocupação é inútil. Deus é misericordioso.'],
            ['category' => 'deus', 'author' => 'Kierkegaard', 'phrase' => 'A oração não muda a Deus, mas muda a quem ora.'],
            ['category' => 'deus', 'author' => 'Santa Teresa de Ávila', 'phrase' => 'Nada te perturbe, nada te espante. Tudo passa, Deus não muda. A paciência tudo alcança.'],

            // evangelica
            ['category' => 'evangelica', 'author' => 'Charles Spurgeon', 'phrase' => 'A ansiedade não esvazia o amanhã das suas tristezas, esvazia o hoje da sua força.'],
            ['category' => 'evangelica', 'author' => 'A.W. Tozer', 'phrase' => 'Um coração cheio de Deus não tem espaço para o medo.'],
            ['category' => 'evangelica', 'author' => 'Billy Graham', 'phrase' => 'A salvação é gratuita, mas o discipulado custa tudo o que temos.'],
            ['category' => 'evangelica', 'author' => 'John Piper', 'phrase' => 'Deus é mais glorificado em nós quando estamos mais satisfeitos Nele.'],
            ['category' => 'evangelica', 'author' => 'Paul Washer', 'phrase' => 'O amor verdadeiro por Deus se traduz em obediência à Sua Palavra.'],
            ['category' => 'evangelica', 'author' => 'Hernandes Dias Lopes', 'phrase' => 'A oração não é um meio de mudarmos a vontade de Deus, mas um meio de alinharmos a nossa vontade à Dele.'],
            ['category' => 'evangelica', 'author' => 'C.S. Lewis', 'phrase' => 'Ser cristão significa perdoar o inescusável porque Deus perdoou o inescusável em você.'],
            ['category' => 'evangelica', 'author' => 'Timothy Keller', 'phrase' => 'O evangelho nos diz que somos mais pecadores do que imaginávamos, mas mais amados do que sonhávamos.'],
            ['category' => 'evangelica', 'author' => 'D.L. Moody', 'phrase' => 'A Bíblia não foi dada para aumentar nosso conhecimento, mas para mudar nossas vidas.'],
            ['category' => 'evangelica', 'author' => 'R.C. Sproul', 'phrase' => 'Nada pode separar-nos do amor de Deus, e nenhum propósito de Deus pode ser frustrado.'],
            ['category' => 'evangelica', 'author' => 'Corrie ten Boom', 'phrase' => 'A fé vê o invisível, acredita no inacreditável e recebe o impossível.'],
            ['category' => 'evangelica', 'author' => 'Max Lucado', 'phrase' => 'A sua fé não é baseada no que você sente, é baseada nas promessas de Deus.'],
            ['category' => 'evangelica', 'author' => 'Rick Warren', 'phrase' => 'O propósito da vida é muito maior do que sua realização pessoal.'],
            ['category' => 'evangelica', 'author' => 'Arthur Pink', 'phrase' => 'Soberania de Deus significa que Ele é Deus e que no trono do universo Ele age conforme lhe apraz.'],
            ['category' => 'evangelica', 'author' => 'John MacArthur', 'phrase' => 'A verdade de Deus é a âncora firme na tempestade do mundo.'],
            ['category' => 'evangelica', 'author' => 'Martyn Lloyd-Jones', 'phrase' => 'A verdadeira religião não é uma fuga da vida, é o poder de vivê-la.'],
            ['category' => 'evangelica', 'author' => 'Augustus Nicodemus', 'phrase' => 'O perdão divino é a essência da nossa salvação.'],
            ['category' => 'evangelica', 'author' => 'J.C. Ryle', 'phrase' => 'Sem santidade, ninguém verá o Senhor.'],
            ['category' => 'evangelica', 'author' => 'Jonathan Edwards', 'phrase' => 'A graça de Deus é suficiente para os piores pecadores.'],
            ['category' => 'evangelica', 'author' => 'John Stott', 'phrase' => 'A cruz de Cristo é a revelação máxima do amor e da justiça de Deus.'],

            // gratidao
            ['category' => 'gratidao', 'author' => 'Cícero', 'phrase' => 'A gratidão não é apenas a maior das virtudes, mas a mãe de todas as outras.'],
            ['category' => 'gratidao', 'author' => 'Eckhart Tolle', 'phrase' => 'Reconhecer o bom que você já tem na sua vida é o fundamento de toda abundância.'],
            ['category' => 'gratidao', 'author' => 'Ralph Waldo Emerson', 'phrase' => 'Cultive o hábito de ser grato por cada coisa boa que lhe chega e de dar graças continuamente.'],
            ['category' => 'gratidao', 'author' => 'Oprah Winfrey', 'phrase' => 'Seja grato pelo que você tem; você acabará tendo mais.'],
            ['category' => 'gratidao', 'author' => 'Epicuro', 'phrase' => 'Não estrague o que você tem desejando o que não tem.'],
            ['category' => 'gratidao', 'author' => 'Seneca', 'phrase' => 'A verdadeira felicidade é desfrutar o presente sem ansiedade.'],
            ['category' => 'gratidao', 'author' => 'Melody Beattie', 'phrase' => 'A gratidão transforma o que temos em suficiente, e mais.'],
            ['category' => 'gratidao', 'author' => 'William Arthur Ward', 'phrase' => 'A gratidão pode transformar dias comuns em dias de ação de graças.'],
            ['category' => 'gratidao', 'author' => 'Albert Schweitzer', 'phrase' => 'A gratidão é o segredo da vida.'],
            ['category' => 'gratidao', 'author' => 'Dietrich Bonhoeffer', 'phrase' => 'Na vida normal de cada dia, muitas vezes não percebemos que recebemos muito mais do que damos.'],
            ['category' => 'gratidao', 'author' => 'Marcel Proust', 'phrase' => 'Sejamos gratos às pessoas que nos fazem felizes; elas são os jardineiros charmosos que fazem nossa alma florescer.'],
            ['category' => 'gratidao', 'author' => 'Aesopo', 'phrase' => 'A gratidão é o sinal de almas nobres.'],
            ['category' => 'gratidao', 'author' => 'Dostoievski', 'phrase' => 'A beleza salvará o mundo, e a gratidão a reconhece.'],
            ['category' => 'gratidao', 'author' => 'Machado de Assis', 'phrase' => 'A gratidão é a memória do coração.'],
            ['category' => 'gratidao', 'author' => 'Dalai Lama', 'phrase' => 'Todos os dias, ao acordar, pense: Que sorte eu tenho de estar vivo.'],
            ['category' => 'gratidao', 'author' => 'Winston Churchill', 'phrase' => 'Nós ganhamos a vida pelo que recebemos, mas fazemos uma vida pelo que damos.'],
            ['category' => 'gratidao', 'author' => 'Buda', 'phrase' => 'Sejamos gratos pelas pequenas coisas.'],
            ['category' => 'gratidao', 'author' => 'Johannes Tauler', 'phrase' => 'Mil agradecimentos não são suficientes por um simples respirar.'],
            ['category' => 'gratidao', 'author' => 'Thornton Wilder', 'phrase' => 'Nós podemos apenas estar vivos naqueles momentos em que o coração está consciente dos nossos tesouros.'],
            ['category' => 'gratidao', 'author' => 'Alice Walker', 'phrase' => 'Obrigado é a melhor oração que alguém poderia dizer.'],

            // indiretas
            ['category' => 'indiretas', 'author' => 'Oscar Wilde', 'phrase' => 'A melhor maneira de apreciar seu trabalho é imaginar-se sem ele.'],
            ['category' => 'indiretas', 'author' => 'Machado de Assis', 'phrase' => 'Aos ignorantes, falta a percepção da própria ignorância.'],
            ['category' => 'indiretas', 'author' => 'Friedrich Nietzsche', 'phrase' => 'Eu não estou chateado porque você mentiu para mim, estou chateado porque de agora em diante não posso acreditar em você.'],
            ['category' => 'indiretas', 'author' => 'Albert Einstein', 'phrase' => 'A diferença entre a genialidade e a estupidez é que a genialidade tem seus limites.'],
            ['category' => 'indiretas', 'author' => 'Mark Twain', 'phrase' => 'Nunca discuta com pessoas estúpidas, elas vão te arrastar ao nível delas e ganhar pela experiência.'],
            ['category' => 'indiretas', 'author' => 'Clarice Lispector', 'phrase' => 'Até cortar os próprios defeitos pode ser perigoso. Nunca se sabe qual é o defeito que sustenta nosso edifício inteiro.'],
            ['category' => 'indiretas', 'author' => 'William Shakespeare', 'phrase' => 'Há mais perigo em teus olhos do que em vinte espadas.'],
            ['category' => 'indiretas', 'author' => 'Voltaire', 'phrase' => 'O segredo de aborrecer é dizer tudo.'],
            ['category' => 'indiretas', 'author' => 'Fernando Pessoa', 'phrase' => 'Às vezes é preciso não fazer nada para perceber que alguns fazem menos ainda.'],
            ['category' => 'indiretas', 'author' => 'Mário Quintana', 'phrase' => 'A mentira é uma verdade que se esqueceu de acontecer.'],
            ['category' => 'indiretas', 'author' => 'Bernard Shaw', 'phrase' => 'O silêncio é a mais perfeita expressão de desprezo.'],
            ['category' => 'indiretas', 'author' => 'Jean-Paul Sartre', 'phrase' => 'O inferno são os outros.'],
            ['category' => 'indiretas', 'author' => 'Schopenhauer', 'phrase' => 'A maior parte das pessoas não sabe escutar.'],
            ['category' => 'indiretas', 'author' => 'Charles Bukowski', 'phrase' => 'Algumas pessoas não têm a capacidade de reconhecer a verdadeira lealdade.'],
            ['category' => 'indiretas', 'author' => 'Zygmunt Bauman', 'phrase' => 'Em um mundo líquido, promessas sólidas incomodam quem não sabe cumprir.'],
            ['category' => 'indiretas', 'author' => 'Agatha Christie', 'phrase' => 'Muito se aprende com quem não sabe nada.'],
            ['category' => 'indiretas', 'author' => 'C.S. Lewis', 'phrase' => 'O orgulho é o pecado original de todas as falhas.'],
            ['category' => 'indiretas', 'author' => 'Eça de Queirós', 'phrase' => 'O riso é a maneira mais fina de não se levar ninguém a sério.'],
            ['category' => 'indiretas', 'author' => 'Platão', 'phrase' => 'Mentes fracas discutem pessoas.'],
            ['category' => 'indiretas', 'author' => 'Cora Coralina', 'phrase' => 'Tem gente que é tão pobre que só tem dinheiro.'],

            // musicas
            ['category' => 'musicas', 'author' => 'Renato Russo', 'phrase' => 'É preciso amar as pessoas como se não houvesse amanhã.'],
            ['category' => 'musicas', 'author' => 'Cazuza', 'phrase' => 'O meu partido é um coração partido.'],
            ['category' => 'musicas', 'author' => 'Bob Marley', 'phrase' => 'Emancipem-se da escravidão mental. Ninguém além de nós mesmos pode libertar nossas mentes.'],
            ['category' => 'musicas', 'author' => 'John Lennon', 'phrase' => 'A vida é o que acontece com você enquanto está ocupado fazendo outros planos.'],
            ['category' => 'musicas', 'author' => 'Raul Seixas', 'phrase' => 'Um sonho que se sonha só é só um sonho que se sonha só, mas sonho que se sonha junto é realidade.'],
            ['category' => 'musicas', 'author' => 'Nando Reis', 'phrase' => 'De todos os loucos do mundo eu quis você, porque a sua loucura parece um pouco com a minha.'],
            ['category' => 'musicas', 'author' => 'Chico Buarque', 'phrase' => 'Apesar de você, amanhã há de ser outro dia.'],
            ['category' => 'musicas', 'author' => 'Freddie Mercury', 'phrase' => 'O show tem que continuar.'],
            ['category' => 'musicas', 'author' => 'Michael Jackson', 'phrase' => 'Se você quer fazer do mundo um lugar melhor, olhe para si mesmo e faça a mudança.'],
            ['category' => 'musicas', 'author' => 'Cássia Eller', 'phrase' => 'Mudaram as estações, nada mudou. Mas eu sei que alguma coisa aconteceu.'],
            ['category' => 'musicas', 'author' => 'Tim Maia', 'phrase' => 'Vale tudo, só não vale dançar homem com homem, nem mulher com mulher... Brincadeira, vale tudo.'],
            ['category' => 'musicas', 'author' => 'Caetano Veloso', 'phrase' => 'Gente é pra brilhar, não pra morrer de fome.'],
            ['category' => 'musicas', 'author' => 'Gilberto Gil', 'phrase' => 'Andar com fé eu vou, que a fé não costuma faiá.'],
            ['category' => 'musicas', 'author' => 'Rita Lee', 'phrase' => 'Um belo dia resolvi mudar e fazer tudo o que eu queria fazer.'],
            ['category' => 'musicas', 'author' => 'Lulu Santos', 'phrase' => 'Nada do que foi será de novo do jeito que já foi um dia.'],
            ['category' => 'musicas', 'author' => 'Alceu Valença', 'phrase' => 'Tu vens, tu vens, eu já escuto os teus sinais.'],
            ['category' => 'musicas', 'author' => 'Elton John', 'phrase' => 'A tristeza é a pior emoção.'],
            ['category' => 'musicas', 'author' => 'Adele', 'phrase' => 'Podíamos ter tido tudo, rolando no abismo.'],
            ['category' => 'musicas', 'author' => 'Ed Sheeran', 'phrase' => 'Nós encontramos o amor bem onde estamos.'],
            ['category' => 'musicas', 'author' => 'Beyoncé', 'phrase' => 'Se você gosta disso, então devia ter colocado um anel.'],

            // sozinha
            ['category' => 'sozinha', 'author' => 'Virginia Woolf', 'phrase' => 'A solitude é a sala de aula da alma.'],
            ['category' => 'sozinha', 'author' => 'Clarice Lispector', 'phrase' => 'Minha solidão não tem nada a ver com a presença ou ausência de pessoas.'],
            ['category' => 'sozinha', 'author' => 'Fernando Pessoa', 'phrase' => 'Amo a solidão porque ela me devolve a mim mesmo.'],
            ['category' => 'sozinha', 'author' => 'Arthur Schopenhauer', 'phrase' => 'A solidão é a sorte de todos os espíritos excepcionais.'],
            ['category' => 'sozinha', 'author' => 'Jean-Paul Sartre', 'phrase' => 'Se você se sente solitário quando está sozinho, está em má companhia.'],
            ['category' => 'sozinha', 'author' => 'C.S. Lewis', 'phrase' => 'Nós lemos para saber que não estamos sozinhos.'],
            ['category' => 'sozinha', 'author' => 'Friedrich Nietzsche', 'phrase' => 'O indivíduo sempre teve que lutar para não ser engolido pela tribo.'],
            ['category' => 'sozinha', 'author' => 'Albert Einstein', 'phrase' => 'É estranho ser conhecido tão universalmente e ainda ser tão solitário.'],
            ['category' => 'sozinha', 'author' => 'Maya Angelou', 'phrase' => 'A solidão é um lugar que às vezes escolho para me curar.'],
            ['category' => 'sozinha', 'author' => 'Hermann Hesse', 'phrase' => 'O homem está sempre fundamentalmente sozinho.'],
            ['category' => 'sozinha', 'author' => 'Carl Jung', 'phrase' => 'Solidão não vem de não ter pessoas ao redor, mas de ser incapaz de comunicar coisas que parecem importantes para si.'],
            ['category' => 'sozinha', 'author' => 'Mário Quintana', 'phrase' => 'A pior solidão é a de quem não sabe se fazer companhia.'],
            ['category' => 'sozinha', 'author' => 'Cecília Meireles', 'phrase' => 'Há momentos em que a maior dádiva é estar sozinho em paz.'],
            ['category' => 'sozinha', 'author' => 'Edgar Allan Poe', 'phrase' => 'Desde a hora da infância não tenho sido como os outros foram.'],
            ['category' => 'sozinha', 'author' => 'Charles Bukowski', 'phrase' => 'A solidão é algo com o qual você se acostuma depois de um tempo.'],
            ['category' => 'sozinha', 'author' => 'Sigmund Freud', 'phrase' => 'Todos nós estamos, em última análise, sozinhos na vida.'],
            ['category' => 'sozinha', 'author' => 'Sylvia Plath', 'phrase' => 'Eu gosto de pessoas, mas adoro a minha própria companhia.'],
            ['category' => 'sozinha', 'author' => 'Franz Kafka', 'phrase' => 'Estou sempre mais solitário no meio da multidão.'],
            ['category' => 'sozinha', 'author' => 'Albert Camus', 'phrase' => 'Para entender o mundo, é preciso se desviar dele ocasionalmente.'],
            ['category' => 'sozinha', 'author' => 'Lygia Fagundes Telles', 'phrase' => 'Eu não estou sozinha, eu estou comigo.'],

            // tristes
            ['category' => 'tristes', 'author' => 'Fernando Pessoa', 'phrase' => 'Tenho em mim todos os sonhos do mundo, mas também todas as desilusões.'],
            ['category' => 'tristes', 'author' => 'Clarice Lispector', 'phrase' => 'A tristeza é um sentimento que a gente abraça quando não há mais ninguém.'],
            ['category' => 'tristes', 'author' => 'Victor Hugo', 'phrase' => 'A melancolia é a felicidade de se estar triste.'],
            ['category' => 'tristes', 'author' => 'Charles Bukowski', 'phrase' => 'O problema com o mundo é que as pessoas inteligentes estão cheias de dúvidas, enquanto os estúpidos estão cheios de confiança.'],
            ['category' => 'tristes', 'author' => 'Mário Quintana', 'phrase' => 'A tristeza é o intervalo entre duas alegrias.'],
            ['category' => 'tristes', 'author' => 'C.S. Lewis', 'phrase' => 'A dor que sinto agora é a felicidade que tive antes. É o acordo.'],
            ['category' => 'tristes', 'author' => 'Machado de Assis', 'phrase' => 'Lágrimas não são argumentos.'],
            ['category' => 'tristes', 'author' => 'Sylvia Plath', 'phrase' => 'É que às vezes a gente se cansa de ser forte.'],
            ['category' => 'tristes', 'author' => 'Oscar Wilde', 'phrase' => 'O coração foi feito para ser partido.'],
            ['category' => 'tristes', 'author' => 'Edgar Allan Poe', 'phrase' => 'Eu fiquei insano, com longos intervalos de horrível sanidade.'],
            ['category' => 'tristes', 'author' => 'Antoine de Saint-Exupéry', 'phrase' => 'É triste esquecer um amigo. Nem todo mundo teve um amigo.'],
            ['category' => 'tristes', 'author' => 'Vinicius de Moraes', 'phrase' => 'Tristeza não tem fim, felicidade sim.'],
            ['category' => 'tristes', 'author' => 'Florbela Espanca', 'phrase' => 'Eu sou a que no mundo anda perdida.'],
            ['category' => 'tristes', 'author' => 'Álvaro de Campos', 'phrase' => 'Não sou nada. Nunca serei nada. Não posso querer ser nada.'],
            ['category' => 'tristes', 'author' => 'Hermann Hesse', 'phrase' => 'Há tristezas que nos fazem envelhecer em um dia.'],
            ['category' => 'tristes', 'author' => 'Franz Kafka', 'phrase' => 'Existem dores que não fazem barulho, mas destroem por dentro.'],
            ['category' => 'tristes', 'author' => 'Virginia Woolf', 'phrase' => 'A dor das despedidas marca a alma com cicatrizes invisíveis.'],
            ['category' => 'tristes', 'author' => 'José Saramago', 'phrase' => 'A pior dor é não ter a quem contar a dor.'],
            ['category' => 'tristes', 'author' => 'Dostoievski', 'phrase' => 'Uma alma despedaçada não encontra consolo no barulho do mundo.'],
            ['category' => 'tristes', 'author' => 'Ernest Hemingway', 'phrase' => 'A forma mais dolorosa de saudade é a de quem ainda está ao seu lado, mas já partiu.'],

            // visao
            ['category' => 'visao', 'author' => 'Sabotage', 'phrase' => 'O rap é compromisso, não é viagem.'],
            ['category' => 'visao', 'author' => 'Mano Brown', 'phrase' => 'A confiança é uma mulher ingrata, que te beija e te abraça, te rouba e te mata.'],
            ['category' => 'visao', 'author' => 'Nelson Mandela', 'phrase' => 'Visão sem ação é apenas um sonho, ação sem visão é apenas um passatempo.'],
            ['category' => 'visao', 'author' => 'Emicida', 'phrase' => 'Irmão, você não percebeu que você é o único representante do seu sonho na face da terra?'],
            ['category' => 'visao', 'author' => 'Racionais MCs', 'phrase' => 'Fé em Deus que Ele é justo!'],
            ['category' => 'visao', 'author' => 'Sun Tzu', 'phrase' => 'A vitória está reservada para aqueles que estão dispostos a pagar o preço.'],
            ['category' => 'visao', 'author' => 'Tupac Shakur', 'phrase' => 'Para cada noite escura, há um dia brilhante.'],
            ['category' => 'visao', 'author' => 'Malcolm X', 'phrase' => 'Educação é o nosso passaporte para o futuro.'],
            ['category' => 'visao', 'author' => 'MV Bill', 'phrase' => 'No jogo da vida, a visão de cria vale mais que diploma.'],
            ['category' => 'visao', 'author' => 'Filipe Ret', 'phrase' => 'A vida é um sopro, então não perca tempo com pouca ideia.'],
            ['category' => 'visao', 'author' => 'Djonga', 'phrase' => 'Fogo nos racistas e visão no futuro.'],
            ['category' => 'visao', 'author' => 'Projota', 'phrase' => 'O foco é a meta, a caminhada é o aprendizado.'],
            ['category' => 'visao', 'author' => 'Martin Luther King Jr.', 'phrase' => 'Suba o primeiro degrau com fé. Não é necessário que você veja toda a escada.'],
            ['category' => 'visao', 'author' => 'Dalai Lama', 'phrase' => 'Uma mente aberta e uma visão clara são as chaves da sabedoria.'],
            ['category' => 'visao', 'author' => 'Bob Marley', 'phrase' => 'Abre os olhos e olha para dentro. Você está satisfeito com a vida que vive?'],
            ['category' => 'visao', 'author' => 'BK', 'phrase' => 'Visão de águia para enxergar além das muralhas do sistema.'],
            ['category' => 'visao', 'author' => 'L7nnon', 'phrase' => 'Fé no processo que o resultado vem em dobro.'],
            ['category' => 'visao', 'author' => 'Edi Rock', 'phrase' => 'É no silêncio que a visão clareia e o progresso acontece.'],
            ['category' => 'visao', 'author' => 'Matuê', 'phrase' => 'Olha pra cima, o topo é o limite para quem tem visão.'],
            ['category' => 'visao', 'author' => 'Dexter', 'phrase' => 'Quem é de verdade sabe quem é de mentira. Pega a visão.'],

            // familia
            ['category' => 'familia', 'author' => 'Papa Francisco', 'phrase' => 'A família é a base da sociedade e o lugar onde aprendemos o valor da vida.'],
            ['category' => 'familia', 'author' => 'Mãe Teresa', 'phrase' => 'O que você pode fazer para promover a paz mundial? Vá para casa e ame sua família.'],
            ['category' => 'familia', 'author' => 'Michael J. Fox', 'phrase' => 'A família não é uma coisa importante. É tudo.'],
            ['category' => 'familia', 'author' => 'Mario Puzo', 'phrase' => 'A força da família, assim como a força de um exército, está na lealdade uns aos outros.'],
            ['category' => 'familia', 'author' => 'Desmond Tutu', 'phrase' => 'Você não escolhe sua família. Eles são o presente de Deus para você, assim como você é para eles.'],
            ['category' => 'familia', 'author' => 'Winston Churchill', 'phrase' => 'Não há dúvida de que é ao redor da família e do lar que todas as maiores virtudes da sociedade são criadas.'],
            ['category' => 'familia', 'author' => 'Walt Disney', 'phrase' => 'Um homem nunca deve negligenciar a sua família em favor dos negócios.'],
            ['category' => 'familia', 'author' => 'Brad Pitt', 'phrase' => 'Ter uma família muda as suas prioridades, muda o foco para o que realmente importa.'],
            ['category' => 'familia', 'author' => 'George Bernard Shaw', 'phrase' => 'A família é um dos milagres da natureza.'],
            ['category' => 'familia', 'author' => 'C.S. Lewis', 'phrase' => 'A verdadeira alegria do lar é a paz que sentimos junto da nossa família.'],
            ['category' => 'familia', 'author' => 'Provérbio Africano', 'phrase' => 'Se quiser ir rápido, vá sozinho. Se quiser ir longe, vá em grupo.'],
            ['category' => 'familia', 'author' => 'Albert Einstein', 'phrase' => 'Regozije-se com sua família no belo lar da vida.'],
            ['category' => 'familia', 'author' => 'Gabriel García Márquez', 'phrase' => 'O laço que une a sua família verdadeira não é de sangue, mas de respeito e alegria na vida um do outro.'],
            ['category' => 'familia', 'author' => 'Liev Tolstói', 'phrase' => 'Todas as famílias felizes se parecem, cada família infeliz é infeliz à sua maneira.'],
            ['category' => 'familia', 'author' => 'Barbara Bush', 'phrase' => 'A família e os amigos são a coisa mais importante do mundo.'],
            ['category' => 'familia', 'author' => 'Anthony Brandt', 'phrase' => 'Outras coisas podem nos mudar, mas nós começamos e terminamos com a família.'],
            ['category' => 'familia', 'author' => 'Jim Rohn', 'phrase' => 'A família e as relações são os bens mais preciosos da nossa vida.'],
            ['category' => 'familia', 'author' => 'Guy de Maupassant', 'phrase' => 'Só se entende o valor de um lar quando nos afastamos da nossa família.'],
            ['category' => 'familia', 'author' => 'J.K. Rowling', 'phrase' => 'A família é o nosso refúgio mais seguro neste mundo instável.'],
            ['category' => 'familia', 'author' => 'Augusto Cury', 'phrase' => 'Construir laços familiares fortes é o maior investimento que podemos fazer.'],

            // falsidade
            ['category' => 'falsidade', 'author' => 'Maquiavel', 'phrase' => 'Os homens em geral julgam mais pelos olhos do que pelas mãos.'],
            ['category' => 'falsidade', 'author' => 'Arthur Schopenhauer', 'phrase' => 'O amigo de todos não é amigo de ninguém.'],
            ['category' => 'falsidade', 'author' => 'Friedrich Nietzsche', 'phrase' => 'Não me chateia o facto de me teres mentido, chateia-me não poder voltar a acreditar em ti.'],
            ['category' => 'falsidade', 'author' => 'William Shakespeare', 'phrase' => 'As pessoas falsas são como moedas; têm duas caras e não valem nada.'],
            ['category' => 'falsidade', 'author' => 'Clarice Lispector', 'phrase' => 'A pior mentira não é aquela que se conta, mas a verdade que se esconde.'],
            ['category' => 'falsidade', 'author' => 'Machado de Assis', 'phrase' => 'O sorriso nos lábios nem sempre é o reflexo de um coração limpo.'],
            ['category' => 'falsidade', 'author' => 'Molière', 'phrase' => 'O hipócrita tem o dom de se ofender quando a verdade bate à sua porta.'],
            ['category' => 'falsidade', 'author' => 'Bob Marley', 'phrase' => 'É nos momentos difíceis que vemos quem realmente são os nossos amigos.'],
            ['category' => 'falsidade', 'author' => 'Sócrates', 'phrase' => 'Cuidado com o lobo vestido em pele de ovelha.'],
            ['category' => 'falsidade', 'author' => 'Platão', 'phrase' => 'A amizade não suporta máscaras.'],
            ['category' => 'falsidade', 'author' => 'C.S. Lewis', 'phrase' => 'O pior de todos os enganos é enganar-se a si próprio acreditando nas próprias mentiras.'],
            ['category' => 'falsidade', 'author' => 'Mark Twain', 'phrase' => 'Uma meia verdade é a mais covarde das mentiras.'],
            ['category' => 'falsidade', 'author' => 'Oscar Wilde', 'phrase' => 'Um pouco de sinceridade é uma coisa perigosa, e muita sinceridade é absolutamente fatal.'],
            ['category' => 'falsidade', 'author' => 'La Rochefoucauld', 'phrase' => 'A hipocrisia é uma homenagem que o vício presta à virtude.'],
            ['category' => 'falsidade', 'author' => 'Buda', 'phrase' => 'Três coisas não podem ser escondidas por muito tempo: o sol, a lua e a verdade.'],
            ['category' => 'falsidade', 'author' => 'Aristóteles', 'phrase' => 'Aquele que mente precisa ter boa memória.'],
            ['category' => 'falsidade', 'author' => 'Sêneca', 'phrase' => 'Nada é tão enganoso quanto o brilho falso de amizades passageiras.'],
            ['category' => 'falsidade', 'author' => 'Mário Quintana', 'phrase' => 'A falsidade é a marca registrada dos espíritos fracos.'],
            ['category' => 'falsidade', 'author' => 'Eça de Queirós', 'phrase' => 'Abraça-te à verdade, pois os abraços da falsidade sufocam.'],
            ['category' => 'falsidade', 'author' => 'Espinosa', 'phrase' => 'A mente percebe rapidamente quando o coração tenta esconder suas intenções reais.'],

            // maloka
            ['category' => 'maloka', 'author' => 'MC Hariel', 'phrase' => 'A caminhada é longa, mas a vitória é certa pra quem trampa na pureza.'],
            ['category' => 'maloka', 'author' => 'MC Kevin', 'phrase' => 'O que importa é a essência, carro zero não muda quem você é.'],
            ['category' => 'maloka', 'author' => 'MC Poze do Rodo', 'phrase' => 'Deus na frente sempre, a favela venceu e vai continuar vencendo.'],
            ['category' => 'maloka', 'author' => 'MC Cabelinho', 'phrase' => 'Pra inveja é tchau, pra falsidade é fogo.'],
            ['category' => 'maloka', 'author' => 'Racionais MCs', 'phrase' => 'A alma guarda o que a mente tenta esquecer. Pega a visão da quebrada.'],
            ['category' => 'maloka', 'author' => 'MC IG', 'phrase' => 'Quem plantou choro, hoje colhe sorriso.'],
            ['category' => 'maloka', 'author' => 'MC Paulin da Capital', 'phrase' => 'O menor que era tirado hoje é inspiração pros bico.'],
            ['category' => 'maloka', 'author' => 'Filipe Ret', 'phrase' => 'Nunca confunda minha simpatia com fraqueza, maloka sabe ser brabo na hora certa.'],
            ['category' => 'maloka', 'author' => 'MC Ryan SP', 'phrase' => 'O tubarão tá na pista e o progresso não para.'],
            ['category' => 'maloka', 'author' => 'MC Neguinho do Kaxeta', 'phrase' => 'Nós viemos de baixo, não é qualquer ventinho que derruba a nossa base.'],
            ['category' => 'maloka', 'author' => 'Djonga', 'phrase' => 'Os menor tem sonho, e sonho de maloka ninguém tira.'],
            ['category' => 'maloka', 'author' => 'MC Lipi', 'phrase' => 'Foi no barro que nós forjou o nosso caráter de ouro.'],
            ['category' => 'maloka', 'author' => 'MC Marks', 'phrase' => 'Deus abençoe o rolê, livra da inveja e atrai só o que for de verdade.'],
            ['category' => 'maloka', 'author' => 'Hungria Hip Hop', 'phrase' => 'Mente rica, bolso cheio, coração blindado e maldade zero.'],
            ['category' => 'maloka', 'author' => 'MC Don Juan', 'phrase' => 'Hoje nós tá bem, mas não esquece de quem fortaleceu no sufoco.'],
            ['category' => 'maloka', 'author' => 'MC Dricka', 'phrase' => 'As patroa tão no toque, maloka não abaixa a cabeça pra playboy.'],
            ['category' => 'maloka', 'author' => 'MC Paiva', 'phrase' => 'A favela tem voz, tem talento e tem progresso. Marcha no trampo.'],
            ['category' => 'maloka', 'author' => 'MC Davi', 'phrase' => 'Aquele que pisou, hoje vê a gente passando de nave no respeito.'],
            ['category' => 'maloka', 'author' => 'MC Léo da Baixada', 'phrase' => 'Humildade prevalece, maloqueiro nato não perde a essência do gueto.'],
            ['category' => 'maloka', 'author' => 'MC GP', 'phrase' => 'De onde nós vem, desistir nunca foi opção. Foco no progresso.'],
        ];

        foreach ($phrases as $phraseData) {
            StatusPhrase::firstOrCreate(
                ['phrase' => $phraseData['phrase']],
                [
                    'category' => $phraseData['category'],
                    'author'   => $phraseData['author'],
                    'likes'    => rand(10, 500)
                ]
            );
        }
    }
}
