<?php

namespace Database\Seeders;

use App\Models\StatusPhrase;
use Illuminate\Database\Seeder;

class StatusPhrasesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $phrases = [
            // =========================================================================
            // AMOR (40 frases)
            // =========================================================================
            ['category' => 'amor', 'phrase' => 'Te amo não apenas pelo que você é, mas pelo que sou quando estou com você.', 'author' => 'Elizabeth Barrett Browning'],
            ['category' => 'amor', 'phrase' => 'O amor não consiste em olhar um para o outro, mas sim em olhar juntos na mesma direção.', 'author' => 'Antoine de Saint-Exupéry'],
            ['category' => 'amor', 'phrase' => 'A medida do amor é amar sem medida.', 'author' => 'Santo Agostinho'],
            ['category' => 'amor', 'phrase' => 'De tudo o que é mais belo no mundo, o seu sorriso é o meu favorito.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Se eu sei o que é o amor, é por sua causa.', 'author' => 'Hermann Hesse'],
            ['category' => 'amor', 'phrase' => 'Você é o meu hoje e todos os meus amanhãs.', 'author' => 'Leo Christopher'],
            ['category' => 'amor', 'phrase' => 'O amor é a poesia dos sentidos.', 'author' => 'Honoré de Balzac'],
            ['category' => 'amor', 'phrase' => 'Estar com você é como caminhar em um jardim florido em plena primavera.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Você é o motivo do meu sorriso mais sincero.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor é apenas uma palavra até que alguém vem e lhe dá sentido.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'A maior felicidade da vida é a convicção de que somos amados.', 'author' => 'Victor Hugo'],
            ['category' => 'amor', 'phrase' => 'Seu carinho acalma minha alma e alegra meu coração.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Te amo ontem, te amo hoje, te amo sempre e para sempre.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Quando o amor é verdadeiro, a distância se torna apenas um detalhe.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor não se vê com os olhos, mas com o coração.', 'author' => 'William Shakespeare'],
            ['category' => 'amor', 'phrase' => 'Você é meu porto seguro, meu refúgio e minha paz.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Amar é encontrar na felicidade do outro a sua própria felicidade.', 'author' => 'Gottfried Leibniz'],
            ['category' => 'amor', 'phrase' => 'Seu amor é o melhor presente que a vida me deu.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Não existem palavras suficientes para expressar o tamanho do meu amor por você.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor é o espaço e o tempo tornados sensíveis ao coração.', 'author' => 'Marcel Proust'],
            ['category' => 'amor', 'phrase' => 'Você é o encaixe perfeito para a minha vida desajeitada.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Eu escolho você todos os dias, sem pensar duas vezes.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor é a única força capaz de transformar um inimigo em amigo.', 'author' => 'Martin Luther King Jr.'],
            ['category' => 'amor', 'phrase' => 'Estar nos seus braços é o meu lugar favorito no mundo.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor cura as pessoas — tanto as que o dão como as que o recebem.', 'author' => 'Karl Menninger'],
            ['category' => 'amor', 'phrase' => 'Com você, cada dia é um novo capítulo de felicidade.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Seu olhar tem a luz que guia o meu caminho.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Amar é dar a alguém a capacidade de te destruir, mas confiar que não o fará.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor é a chave mestre que abre os portões da felicidade.', 'author' => 'Oliver Wendell Holmes'],
            ['category' => 'amor', 'phrase' => 'Você é tudo o que eu sempre quis e um pouco mais.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'A vida é muito mais doce com você ao meu lado.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor verdadeiro começa quando nada se espera em troca.', 'author' => 'Antoine de Saint-Exupéry'],
            ['category' => 'amor', 'phrase' => 'Meu lar é onde você estiver.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'A flor precisa de sol para viver, eu preciso de você para ser feliz.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Quem ama sabe que o tempo não passa, apenas se vive na eternidade.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Cada detalhe seu me faz apaixonar cada dia mais.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor é a beleza da alma.', 'author' => 'Santo Agostinho'],
            ['category' => 'amor', 'phrase' => 'No oceano da vida, você é a minha âncora.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'Você trouxe cores novas para pintar o meu mundo cinza.', 'author' => null],
            ['category' => 'amor', 'phrase' => 'O amor verdadeiro é aquele que resiste ao teste do tempo.', 'author' => null],

            // =========================================================================
            // AMIZADE (40 frases)
            // =========================================================================
            ['category' => 'amizade', 'phrase' => 'Um amigo de verdade é alguém que caminha para dentro quando todos os outros caminham para fora.', 'author' => 'Walter Winchell'],
            ['category' => 'amizade', 'phrase' => 'A amizade duplica as alegrias e divide as tristezas ao meio.', 'author' => 'Francis Bacon'],
            ['category' => 'amizade', 'phrase' => 'Amigos são a família que nós mesmos escolhemos.', 'author' => 'Jess C. Scott'],
            ['category' => 'amizade', 'phrase' => 'A amizade é o ingrediente mais importante na receita da vida.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Um amigo é alguém que conhece a sua música e a canta para você quando você a esquece.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Bons amigos são como estrelas: você nem sempre os vê, mas sabe que estão lá.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A verdadeira amizade não se baseia em ser inseparável, mas em estar separado e nada mudar.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A melhor maneira de começar uma amizade é com um belo sorriso.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Quem tem um amigo de verdade, tem um tesouro valioso para toda a vida.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A amizade é uma alma que habita em dois corpos; um coração que bate em duas almas.', 'author' => 'Aristóteles'],
            ['category' => 'amizade', 'phrase' => 'Amizade verdadeira não é sobre quem veio primeiro, mas sobre quem veio e nunca te abandonou.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Rir com um amigo é a melhor terapia que existe.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A amizade é o amor sem asas, puro e sem complicações.', 'author' => 'Lord Byron'],
            ['category' => 'amizade', 'phrase' => 'Ter um amigo de verdade é saber que você nunca passará por momentos difíceis sozinho.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Os amigos são os irmãos que Deus esqueceu de nos dar.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A amizade desenvolve a felicidade e reduz o sofrimento, duplicando nossa alegria e dividindo nossa dor.', 'author' => 'Cícero'],
            ['category' => 'amizade', 'phrase' => 'Agradeço todos os dias pelas risadas compartilhadas e segredos guardados.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Um amigo verdadeiro te apoia nas suas loucuras e te segura na hora de cair.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A amizade é como as flores: precisa ser regada e cuidada com carinho todos os dias.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Não há solidão mais triste do que a do homem sem amigos.', 'author' => 'Francis Bacon'],
            ['category' => 'amizade', 'phrase' => 'Os amigos escutam o que você diz. Os melhores amigos escutam o que você não diz.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Amizades puras resistem ao tempo, à distância e aos silêncios.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'O melhor espelho é um velho amigo.', 'author' => 'George Herbert'],
            ['category' => 'amizade', 'phrase' => 'Com vocês, as risadas são mais altas e as dores são mais leves.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A amizade é o maior dos prazeres e o mais doce dos confortos.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Encontrar amigos com a mesma loucura que você não tem preço.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Os verdadeiros amigos entram na nossa vida para nos fazer enxergar o nosso melhor.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Amigo é aquele que te faz sorrir mesmo quando a sua vontade é chorar.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Nenhuma estrada é longa demais quando temos boa companhia.', 'author' => 'Provérbio Turco'],
            ['category' => 'amizade', 'phrase' => 'A amizade é a linha dourada que une o coração de todo o mundo.', 'author' => 'John Evelyn'],
            ['category' => 'amizade', 'phrase' => 'Os amigos nos ensinam que a felicidade fica mais bonita quando compartilhada.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Guardar um amigo no peito é ter a certeza de que a vida vale a pena.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A amizade é a única cura para as dores do mundo.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'O amor é bom, mas ter amigos é ter uma fortaleza inabalável.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Um brinde às amizades que começaram do nada e hoje são tudo.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A distância pode impedir um abraço, mas nunca a força de uma grande amizade.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Amigos nos ajudam a levantar quando as nossas asas esquecem como voar.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'A amizade é um contrato pelo qual nos obrigamos a prestar pequenos serviços para receber grandes.', 'author' => 'Montesquieu'],
            ['category' => 'amizade', 'phrase' => 'A vida é curta, mas as boas amizades a tornam eterna.', 'author' => null],
            ['category' => 'amizade', 'phrase' => 'Obrigado por estar lá nos momentos mais difíceis e nos mais felizes também.', 'author' => null],

            // =========================================================================
            // MOTIVAÇÃO (40 frases)
            // =========================================================================
            ['category' => 'motivacao', 'phrase' => 'O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.', 'author' => 'Winston Churchill'],
            ['category' => 'motivacao', 'phrase' => 'A única maneira de fazer um excelente trabalho é amar o que você faz.', 'author' => 'Steve Jobs'],
            ['category' => 'motivacao', 'phrase' => 'Acredite que você pode e você já estará no meio do caminho.', 'author' => 'Theodore Roosevelt'],
            ['category' => 'motivacao', 'phrase' => 'O que não nos mata nos torna mais fortes.', 'author' => 'Friedrich Nietzsche'],
            ['category' => 'motivacao', 'phrase' => 'Não espere por circunstâncias ideais. Crie as suas próprias oportunidades.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'O fracasso é a oportunidade de começar de novo, com mais inteligência.', 'author' => 'Henry Ford'],
            ['category' => 'motivacao', 'phrase' => 'Nenhum obstáculo é grande demais se a sua vontade de vencer for maior.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Se você pode sonhar, você pode realizar.', 'author' => 'Walt Disney'],
            ['category' => 'motivacao', 'phrase' => 'Lembre-se: o sol sempre volta a brilhar após a pior das tempestades.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'A persistência é o caminho do êxito.', 'author' => 'Charles Chaplin'],
            ['category' => 'motivacao', 'phrase' => 'Tudo o que a mente humana pode conceber e acreditar, ela pode alcançar.', 'author' => 'Napoleon Hill'],
            ['category' => 'motivacao', 'phrase' => 'Dificuldades preparam pessoas comuns para destinos extraordinários.', 'author' => 'C.S. Lewis'],
            ['category' => 'motivacao', 'phrase' => 'Não olhe para trás, você não está indo para lá.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Você é muito mais forte do que imagina. Apenas continue caminhando.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso.', 'author' => 'Albert Schweitzer'],
            ['category' => 'motivacao', 'phrase' => 'A sua única limitação é aquela que você impõe a si mesmo.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Comece onde você está, use o que você tem e faça o que você pode.', 'author' => 'Arthur Ashe'],
            ['category' => 'motivacao', 'phrase' => 'A disciplina é a ponte entre as metas e as realizações.', 'author' => 'Jim Rohn'],
            ['category' => 'motivacao', 'phrase' => 'Grandes coisas nunca vêm de zonas de conforto.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Seja a mudança que você deseja ver no mundo.', 'author' => 'Mahatma Gandhi'],
            ['category' => 'motivacao', 'phrase' => 'Caia sete vezes, levante-se oito.', 'author' => 'Provérbio Japonês'],
            ['category' => 'motivacao', 'phrase' => 'A força não vem da capacidade física, vem de uma vontade indomável.', 'author' => 'Mahatma Gandhi'],
            ['category' => 'motivacao', 'phrase' => 'Não pare até se orgulhar de você mesmo.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Cada novo dia é uma nova página em branco para escrever uma vitória.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'O melhor guerreiro não é o que sempre vence, mas o que nunca desiste de lutar.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Sua jornada pode ser lenta, mas desde que não pare, você alcançará o topo.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Os problemas são oportunidades para demonstrarmos o nosso melhor.', 'author' => 'Duke Ellington'],
            ['category' => 'motivacao', 'phrase' => 'A vitória cabe àquele que resiste mais tempo.', 'author' => 'Napoleão Bonaparte'],
            ['category' => 'motivacao', 'phrase' => 'Foque no progresso, não na perfeição.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Sua atitude determina a sua altitude.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'A melhor maneira de prever o futuro é criá-lo.', 'author' => 'Peter Drucker'],
            ['category' => 'motivacao', 'phrase' => 'Não crie limites para si mesmo; crie asas.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Se o plano A não funcionar, lembre-se que o alfabeto tem mais 25 letras.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'O sucesso é a soma de pequenos esforços repetidos dia após dia.', 'author' => 'Robert Collier'],
            ['category' => 'motivacao', 'phrase' => 'Seja mais forte do que a sua melhor desculpa.', 'author' => null],
            ['category' => 'motivacao', 'phrase' => 'Você não falha até que desista de tentar.', 'author' => 'Albert Einstein'],
            ['category' => 'motivacao', 'phrase' => 'Mantenha os olhos nas estrelas e os pés no chão.', 'author' => 'Theodore Roosevelt'],
            ['category' => 'motivacao', 'phrase' => 'Não deixe o ruído das opiniões alheias abafar a sua voz interior.', 'author' => 'Steve Jobs'],
            ['category' => 'motivacao', 'phrase' => 'Quem quer vencer um obstáculo deve armar-se da força do leão e da prudência da serpente.', 'author' => 'Maquiavel'],
            ['category' => 'motivacao', 'phrase' => 'Acredite na beleza dos seus sonhos e caminhe firme em direção a eles.', 'author' => null],

            // =========================================================================
            // ENGRAÇADO (40 frases)
            // =========================================================================
            ['category' => 'engracado', 'phrase' => 'Eu não sou preguiçoso, estou apenas no modo de economia de energia.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Minha carteira é igual a cebola: quando eu abro, dá vontade de chorar.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Dizem que o dinheiro não traz felicidade, mas eu gostaria de chorar dentro de uma Ferrari.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Se a vida te der limões, faça uma limonada e procure alguém cuja vida deu tequila.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Siga o seu coração, mas leve o seu cérebro junto com você por segurança.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'O cérebro é um órgão maravilhoso: começa a funcionar quando acordamos e só para na prova.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'A vida é curta demais para ler termos e condições de uso de aplicativos.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Eu não preciso de um terapeuta, preciso de um boleto pago.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Minhas plantas estão tão secas que o cacto me pediu um copo de água.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Se você cair, eu estarei lá para te levantar. Mas só depois que eu parar de rir.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Relação estável: eu e minha vontade constante de comer alguma coisa.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'A paciência é uma virtude, mas eu não sou muito virtuoso a essa hora do dia.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'A culinária é uma arte. Minha especialidade é queimar miojo.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Fazer caminhada é bom: você caminha, respira ar puro e percebe como seu condicionamento é péssimo.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Dizem que tudo passa na vida. Mas a minha fatura do cartão insiste em ficar.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Inteligência me persegue, mas eu sou mais rápido e consigo fugir dela.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Nunca desista do seu sonho. Se não der certo em uma padaria, tente em outra.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Estou precisando de férias de 3 meses, duas vezes por ano.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Minha conta bancária está em uma dieta super rigorosa ultimamente.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Se ferradura desse sorte, burro não puxava carroça na rua.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Status: procurando um investidor-anjo que aceite pagar minhas contas básicas.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Se você acha que ninguém se importa se você está vivo, tente atrasar uma conta.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'O amor está no ar... mas o Wi-Fi está muito mais rápido e estável.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'A grama do vizinho é mais verde porque ela é sintética, certeza.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Se a vida está difícil para mim, imagina para quem não tem beleza nenhuma para compensar.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Diga-me com quem andas e eu te direi se vou junto ou se fico em casa dormindo.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Eu tenho um relacionamento sério com a minha cama, mas o despertador vive nos separando.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Não deixe para amanhã o que você pode comer hoje mesmo.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Acordei cedo para correr... correr da realidade das minhas obrigações.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Minha paciência é igual a sinal de celular no meio do mato: some do nada.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Eu sou aquela pessoa que olha para os dois lados antes de atravessar uma rua de mão única.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Evite ressacas: mantenha-se bêbado o tempo todo. Brincadeira, beba água.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Se fofoca fosse trabalho, eu já estaria milionário e aposentado.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Eu falo sozinho porque gosto de conversar com pessoas inteligentes e interessantes.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'A vida me derruba, mas eu aproveito para tirar um cochilo no chão quente.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Dormir é muito bom: é como estar morto, mas sem o compromisso de ficar enterrado.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'O dinheiro não compra amor, mas ajuda a pagar o jantar romântico em um restaurante caro.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Sou muito bom na cama: durmo mais de 10 horas seguidas sem acordar nenhuma vez.', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Trabalhar duro nunca matou ninguém, mas por que correr o risco de ser o primeiro?', 'author' => null],
            ['category' => 'engracado', 'phrase' => 'Não sou teimoso, sou apenas focado em provar que estou absolutamente certo.', 'author' => null],

            // =========================================================================
            // REFLEXÃO (40 frases)
            // =========================================================================
            ['category' => 'reflexao', 'phrase' => 'A vida é aquilo que acontece enquanto estamos ocupados fazendo outros planos.', 'author' => 'John Lennon'],
            ['category' => 'reflexao', 'phrase' => 'Conhece-te a ti mesmo e conhecerás o universo e os deuses.', 'author' => 'Sócrates'],
            ['category' => 'reflexao', 'phrase' => 'Penso, logo existo.', 'author' => 'René Descartes'],
            ['category' => 'reflexao', 'phrase' => 'O homem é a medida de todas as coisas.', 'author' => 'Protágoras'],
            ['category' => 'reflexao', 'phrase' => 'Tudo o que sabemos é uma gota de água; o que ignoramos é um oceano inteiro.', 'author' => 'Isaac Newton'],
            ['category' => 'reflexao', 'phrase' => 'A felicidade não é algo pronto. Ela vem das suas próprias ações cotidianas.', 'author' => 'Dalai Lama'],
            ['category' => 'reflexao', 'phrase' => 'Não vemos as coisas como elas são, mas como nós somos.', 'author' => 'Anaïs Nin'],
            ['category' => 'reflexao', 'phrase' => 'A pressa é a inimiga da perfeição, mas a lentidão gera a estagnação.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'O silêncio é, às vezes, a resposta mais eloquente e verdadeira.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'Não espere que o mundo mude para você mudar a sua própria vida.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'A única constante na vida é a mudança.', 'author' => 'Heráclito'],
            ['category' => 'reflexao', 'phrase' => 'Julgar os outros é o caminho mais curto para esquecer de si mesmo.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'A vida é uma peça de teatro que não permite ensaios. Por isso, cante, chore e dance.', 'author' => 'Charles Chaplin'],
            ['category' => 'reflexao', 'phrase' => 'Nós somos o que fazemos repetidamente. A excelência, portanto, não é um ato, mas um hábito.', 'author' => 'Aristóteles'],
            ['category' => 'reflexao', 'phrase' => 'A simplicidade é o último grau da sofisticação elegante.', 'author' => 'Leonardo da Vinci'],
            ['category' => 'reflexao', 'phrase' => 'O segredo da felicidade é a liberdade, e o segredo da liberdade é a coragem.', 'author' => 'Tucídides'],
            ['category' => 'reflexao', 'phrase' => 'A beleza das coisas existe na mente de quem as contempla com amor.', 'author' => 'David Hume'],
            ['category' => 'reflexao', 'phrase' => 'O verdadeiro sábio é aquele que reconhece a sua própria ignorância.', 'author' => 'Sócrates'],
            ['category' => 'reflexao', 'phrase' => 'Quem tem um porquê para viver pode suportar quase qualquer como.', 'author' => 'Friedrich Nietzsche'],
            ['category' => 'reflexao', 'phrase' => 'Não fomos feitos para acumular coisas, mas sim para viver e partilhar momentos.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'A vida sem reflexão não vale a pena ser vivida por um ser humano.', 'author' => 'Sócrates'],
            ['category' => 'reflexao', 'phrase' => 'A maior glória não está em nunca cair, mas em levantar-se a cada queda.', 'author' => 'Confúcio'],
            ['category' => 'reflexao', 'phrase' => 'Pequenas decisões diárias constroem o grande destino da sua existência.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'Seja paciente com você mesmo. Crescer é um processo lento e silencioso.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'A verdade dói por um momento; a mentira corrói a alma pela vida inteira.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'Aprendi que as pessoas esquecerão o que você disse, mas nunca como as fez sentir.', 'author' => 'Maya Angelou'],
            ['category' => 'reflexao', 'phrase' => 'O coração tem razões que a própria razão desconhece por completo.', 'author' => 'Blaise Pascal'],
            ['category' => 'reflexao', 'phrase' => 'Viver é desenhar sem borracha para apagar os erros cometidos.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'A compaixão pelos animais está intimamente ligada à bondade de caráter do homem.', 'author' => 'Arthur Schopenhauer'],
            ['category' => 'reflexao', 'phrase' => 'Não viva no passado, não sonhe com o futuro, concentre a mente no momento presente.', 'author' => 'Buda'],
            ['category' => 'reflexao', 'phrase' => 'O tempo que você gosta de perder não é tempo perdido na sua vida.', 'author' => 'Bertrand Russell'],
            ['category' => 'reflexao', 'phrase' => 'Ser feliz é reconhecer que a vida vale a pena ser vivida apesar de todos os pesares.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'Ninguém pode fazer você se sentir inferior sem o seu consentimento expresso.', 'author' => 'Eleanor Roosevelt'],
            ['category' => 'reflexao', 'phrase' => 'A vida é uma colheita constante daquilo que plantamos ao longo dos dias.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'Não procure a felicidade fora; ela reside no espaço sagrado do seu coração.', 'author' => null],
            ['category' => 'reflexao', 'phrase' => 'Para cada minuto que você passa com raiva, perde sessenta segundos de paz de espírito.', 'author' => 'Ralph Waldo Emerson'],
            ['category' => 'reflexao', 'phrase' => 'A mente que se abre a uma nova ideia jamais voltará ao seu tamanho original.', 'author' => 'Albert Einstein'],
            ['category' => 'reflexao', 'phrase' => 'Conquistar a si mesmo é uma vitória maior do que conquistar milhares em uma batalha.', 'author' => 'Buda'],
            ['category' => 'reflexao', 'phrase' => 'A vida só pode ser compreendida olhando para trás, mas só pode ser vivida olhando para frente.', 'author' => 'Søren Kierkegaard'],
            ['category' => 'reflexao', 'phrase' => 'Seja leve, releve, eleve, ame e viva com sabedoria.', 'author' => null],
        ];

        foreach ($phrases as $phraseData) {
            StatusPhrase::create($phraseData);
        }
    }
}
